### ISSUE TITLE
Admin Page - Resource Object Not Found

### ISSUE THREAD

**Issue by ChrisRomp** [SalesforceLabs/Chatter-for-SharePoint-2010#3]
When accessing the Chatter admin page from Central Admin, I get the error trace below (from log - friendly error just says "The resource object with key 'settings_page_title' was not found.").  I've removed and re-deployed the solution files, re-run Install-SPApplicationContent, etc.

System.Web.HttpException: The resource object with key 'settings_page_title' was not found.
    at System.Web.Compilation.ResourceExpressionBuilder.ParseExpression(String expression, Type propertyType, ExpressionBuilderContext context)     at Microsoft.SharePoint.Search.SPSatelliteResourceExpressionBuilder.ParseExpression(String expression, Type propertyType, ExpressionBuilderContext context)
    at System.Web.UI.BoundPropertyEntry.ParseExpression(ExpressionBuilderContext context)
    at System.Web.UI.ControlBuilder.FillUpBoundPropertyEntry(BoundPropertyEntry entry, String name)
    at System.Web.UI.ControlBuilder.AddBoundProperty(String filter, String name, String expressionPrefix, String expression, ExpressionBuilder expressionBuilder, Object parsedExpressionData, Boolean generated, String fieldName, String formatString, Boolean twoWayBound)
    at System.Web.UI.ControlBuilder.PreprocessAttribute(String filter, String attribname, String attribvalue, Boolean mainDirectiveMode)
    at System.Web.UI.ControlBuilder.PreprocessAttributes(ParsedAttributeCollection attribs)
    at System.Web.UI.ControlBuilder.Init(TemplateParser parser, ControlBuilder parentBuilder, Type type, String tagName, String id, IDictionary attribs)
    at System.Web.UI.ControlBuilder.CreateBuilderFromType(TemplateParser parser, ControlBuilder parentBuilder, Type type, String tagName, String id, IDictionary attribs, Int32 line, String sourceFileName)
    at System.Web.UI.ControlBuilder.CreateChildBuilder(String filter, String tagName, IDictionary attribs, TemplateParser parser, ControlBuilder parentBuilder, String id, Int32 line, VirtualPath virtualPath, Type& childType, Boolean defaultProperty)
    at System.Web.UI.TemplateParser.ProcessBeginTag(Match match, String inputText)
    at System.Web.UI.TemplateParser.ParseStringInternal(String text, Encoding fileEncoding)

**Comment by ChrisRomp** [comment]
Fixed by running Install-SPApplicationContent from the app server that hosts central admin (was running from WFE previously).
